# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup Yarn
      uses: mskelton/setup-yarn@v1.6.0
      #with:
        # Additional flags to pass to the install command.
        #flags: # optional
        # Node version to use, defaults to the current LTS version.
        #node-version: # optional, default is 18.x
        # Git ref to checkout. Passed to `actions/checkout`.
        #ref: # optional
        # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
        #cache: # optional, default is yarn
        # Fetch depth of the checkout. Passed to `actions/checkout`.
        #fetch-depth: # optional
    - run: yarn install --frozen-lockfile
    - run: yarn workspace @beamerstream/control build
